### ISSUE TITLE
Barapost error

### ISSUE THREAD

**Issue by nikolaichik** [masikol/barapost#1]
Hi!

./barapost-v3-5d.py fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0.fastq -l myGenome.fa

results in this:

 |=== barapost-v3-5d.py ===|

   !! - ERROR: fatal error. Please, contact the developer.

Well, I'm consulting))

**Comment by nikolaichik** [comment]
(That was on Ubuntu 16.04 python 3.7.3)

**Comment by masikol** [comment]
Hello!
Thank you for reporting.
This bug is now fixed. New version (barapost-v3-5e.py) is available.

**Comment by nikolaichik** [comment]
Thanks for the quick fix!

However, the thing still doesn't work for me. I'm trying to separate fast5 files matching a single local genome sequence, so running the prober script is  unnecessary (and can actually hamper sorting). So I'm starting with barapost and local genome, but barapost still creates the prober_result dir (which is empty), the sorter script looks for data in it and exits with error. 

Looks like the sorter script (or the docs) needs correction

**Comment by masikol** [comment]
1. Unfortunatelly, I still cannot reproduce the creation of an empty directory named 'prober_result' by "barapost-v3-5e.py". Is this empty directory the only result that "barapost" generates?

2. If it isn't, you can explicitly specify the result directory generated by "barapost" to "fastQA5-sorter" using '-r' option. It was indeed not that clear in readme, so I have rewritten the description (see description of '-r' option in "barapost" and "fastQA5 sorter" sections).

3. Anyway, some steps to prevent behavior described in paragraph '1.' have been made. Briefly, default name of directory with results of taxonomic annotation is now always 'barapost_result' (i.e. it no longer depends on use case). New versions of scripts are now available.

**Comment by nikolaichik** [comment]
1) the empty 'prober_result' dir is still created with barapost-v3-5f.py. Another dir 'barapost_result' is also created and it does contain some results

2) If I add -r barapost_result to the sorter script command, it gives this error:
   !! - ERROR: read 'read_000237b3-bce9-4aec-b301-7f28af9a624f' not found in 'barapost_result' result file

3) fastQA5-sorter.py still looks for prober_result by default.


Obviously, there are problems with file/dir naming resulting in errors. Please note the names of the fast5 and fastq files (the last one given by guppy). I'm reproducing commands, resulting file/dir names and sorter script messages below.

./barapost-v3-5f.py fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0.fastq -l 2A.fa

this gives the 'barapost_result' with the following content:

-rw-rw-r-- 2983 barapost_log_2019-10-26_23-00-50.log
drwxrwxr-x 4096 fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0
drwxrwxr-x 4096 local_database


./fastQA5-sorter-v3-2a.py FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5 -r barapost_result
 
 |=== fastQA5-sorter-v3-2a.py ===|

00:00:02 (2019.10.26 23:06:00) - Start working

 - Sorting sensitivity: 'genus';
 - Minimum mean Phred33 quality of a read to keep: 20;
 - Minimum length of a read to keep: unlimited;


Following files will be processed:
  1. /home/yevgeny/F5T/FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0.fast5
--------------------

00:00:02 - 'FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0.fast5': start sorting

   !! - ERROR: read 'read_000237b3-bce9-4aec-b301-7f28af9a624f' not found in 'barapost_result' result file

Make sure that this read has been already processed by 'prober-v1-12e.py' and 'barapost-v3-5e.py'.

**Comment by nikolaichik** [comment]
A side note: why change script names with every fix? That's very inconvenient! version numbers should be inside and accessible with smth like  script_name.py -v

**Comment by masikol** [comment]
Sure, versions in script names may look strange, but they can be useful, especially when software is in process of developing (just like Barapost) and annoying errors occur quite often. A user can forget to provide a developer with a version of a program which produces errors, but often specifies a command that he runs and that leads to error.

For example, I can see, what version of sorter script you are using directly from the command that you run:

`./fastQA5-sorter-v3-2a.py FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5 -r barapost_result`

Version in script's name can help me to solve a problem that you are facing without asking additional questions (sure, in this case I can see version from script's output, but the idea remains the same).

So, the solution is: this version (3.2.a) of sorter used to look for 'prober_result' directory. Neither does sorter of 3.2.b version, that is available since october 26 afternoon: it looks for 'barapost_result' directory.

So, at least one problem seems to be solved now:

> 3. fastQA5-sorter.py still looks for prober_result by default.

------

Situation with another issue:

> !! - ERROR: read 'read_000237b3-bce9-4aec-b301-7f28af9a624f' not found in 'barapost_result' 
> result file

can be made more clear, if you send me the TSV file generated by 'barapost'. Name of this file:
`barapost_result/fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0/fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0_megaBlast_result.tsv`

-----

The fact that "barapost-v3-5f.py" creates an empty directory besides informative one is still confusing: I cannot made this script act in this way. The string "prober_result" does not even occur in source code since 3.5.f version.

**Comment by nikolaichik** [comment]
> A user can forget to provide a developer with a version of a program which produces errors, but often specifies a command that he runs and that leads to error.

As you can see, it's easier to forget unusual naming scheme and launch wrong script version! So, this idea clearly doesn't work.

Newer script doesn't work at all:
`./fastQA5-sorter-v3-2b.py FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5 -r barapost_result

 |=== fastQA5-sorter-v3-2b.py ===|


   !! - ERROR: invalid positional argument: 'FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5'

Only FAST(A/Q/5) files can be specified without a key in command line.
`

> Situation with another issue:

    !! - ERROR: read 'read_000237b3-bce9-4aec-b301-7f28af9a624f' not found in 'barapost_result'
    result file

can be made more clear, if you send me the TSV file generated by 'barapost'. 

[fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0_megaBlast_result.tsv.gz](https://github.com/masikol/barapost/files/3775535/fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0_megaBlast_result.tsv.gz)

**Comment by masikol** [comment]
> As you can see, it's easier to forget unusual naming scheme and launch wrong script version! So, this idea clearly doesn't work.

I see. Persuasive. Got it.

-----

> Newer script doesn't work at all:
> ./fastQA5-sorter-v3-2b.py FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5 -r barapost_result

Embarrassing... I have not changed the code that is responsible for command-line arguments handling. I have tested sorter for several times, passing FAST5 files to it, and it accepts all of them.

However, this error is reproducible. It can occur when FAST5 file that you specify does not exist or has been moved to another directory.

It is not very possible, that you have forgotten about moving your files to another directory, but check it, please. This error is just as weird as it can be.

-----

> !! - ERROR: read 'read_000237b3-bce9-4aec-b301-7f28af9a624f' not found in 'barapost_result' result file

There are really no line with information about this read in the file you've sent to me. Sorter actualy searches for `000237b3-bce9-4aec-b301-7f28af9a624f`, without `read_` part, because Guppy prunes this part of read ID.

`e6f2851ddd414655574208c18f2f51e590bf4b27_0` parts of your FASTQ and FAST5 file names are identical:

> ./barapost-v3-5f.py fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0.fastq -l 2A.fa

> ./fastQA5-sorter-v3-2b.py FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5 -r barapost_result

From sorter's output I can infer, that sorter successfully finds TSV file with 'barapost' results.

Therefore the only possible reason for not finding this read in TSV file: FASTQ and FAST5 files mentioned above contain different reads. Please, search for `000237b3-bce9-4aec-b301-7f28af9a624f` sequence ID in `fastq_runid_e6f2851ddd414655574208c18f2f51e590bf4b27_0_0.fastq` file.

**Comment by nikolaichik** [comment]
>Therefore the only possible reason for not finding this read in TSV file: FASTQ and FAST5 files mentioned above contain different reads.

This explanation appeared to be correct. Apparently, guppy assigns filenames to fastq files in wrong order (at least on my machine). That read from 0-indexed file appeared in the fastq file with index 21. 

I've also checked another fastq/fast5 pair. Missing read from _1_0.fastq was present in _51.fast5. So, file numbers can't be relied upon!

**Comment by masikol** [comment]
> Apparently, guppy assigns filenames to fastq files in wrong order (at least on my machine).

Appears, this problem occurs not only on your machine. I have checked another data set processed by Guppy -- same thing. I will contact Guppy's support.

The reason why I have not noticed this problem before is that I was "lucky" to choose (for testing purposes, while developing FAST5 sorting) the only two FASTQ-FAST5 pairs that do match one another from the entire data set.

**Comment by masikol** [comment]
Two more questions:

1. Can you tell me, what version of Guppy have you used?

2. Do following problems still remain?

> Newer script doesn't work at all
> !! - ERROR: invalid positional argument:
> 'FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5'

> the empty 'prober_result' dir is still created with barapost-v3-5f.py.

**Comment by nikolaichik** [comment]
>Can you tell me, what version of Guppy have you used?

3.2.4

>Do following problems still remain?

Newer script doesn't work at all
!! - ERROR: invalid positional argument:
'FAK94973_e6f2851ddd414655574208c18f2f51e590bf4b27_0.fast5'

I don't see this error now, just the error about missing read&

>the empty 'prober_result' dir is still created with barapost-v3-5f.py.

no such empty dir either. It's quite possible I was actually launching the previous script version

**Comment by masikol** [comment]
Well, thanks a lot for helping!

**Comment by masikol** [comment]
Hello!

I have some news about this problem:

> guppy assigns filenames to fastq files in wrong order

To sort FAST5 files that do not match FASTQ, you can run sorter with `-u` flag -- it will map reads from FAST5 to their taxonomic annotation in TSV files and sort reads according to this "index". You can see "FAST5 untwisting" section in "README.md" for details.

If sorter results in "reads from FAST5 file not found" error, you can run the "auxiliary/BCsummarizer.py" script and see, which FASTQ file(s) correspond(s) to FAST5 file you need to sort.

**Comment by nikolaichik** [comment]
Still doesn't work.

$ fastQA5-sorter.py -d F5 -r barapost_result

 |=== fastQA5-sorter.py (version 3.3.d) ===|

Primary validation...
   !! - ERROR: directory that may be considered as valid for sorting of file
      '/home/yevgeny/F5T/Single/F5/000237b3-bce9-4aec-b301-7f28af9a624f.fast5'
    is not found in the directory 'barapost_result'

Try running sorter with '-u' ('--untwist-fast5') flag.

$ fastQA5-sorter.py -d F5 -r barapost_result -u

 |=== fastQA5-sorter.py (version 3.3.d) ===|

Primary validation...  ✔

00:00:01 (2019.11.11 22:02:51) - Start working

 - Sorting sensitivity: 'genus';
 - Minimum mean Phred33 quality of a read to keep: 20;
 - Minimum length of a read to keep: unlimited;
 - "FAST5 untwisting" is enabled.


Following files will be processed:
  1. F5/000237b3-bce9-4aec-b301-7f28af9a624f.fast5
  2. F5/000df299-98bb-4101-a1f5-9840693b3d28.fast5

..

  3999. F5/ffde8a2e-1d26-43c2-a8f9-dbb1526700e5.fast5
  4000. F5/fff0070d-43da-41e1-a163-db240bf3586f.fast5
--------------------

00:00:02 - Untwisting started.
Untwisting reads in '000237b3-bce9-4aec-b301-7f28af9a624f.fast5'...
   !! - ERROR: reads from FAST5 file not found

FAST5 file: 'F5/000237b3-bce9-4aec-b301-7f28af9a624f.fast5'
Some reads reads have not undergone taxonomic annotation.
List of missing reads are in following file:
  'missing_reads_lst.txt'

Contents of the missing_reads_lst.txt :
Missing reads from file '/home/yevgeny/F5T/Single/F5/000237b3-bce9-4aec-b301-7f28af9a624f.fast5':

Raw
UniqueGlobalKey

$ BCsummarizer.py -5 F5 -q BaseCalled

(manu unhelpful letters)
00:00:04 - 'fff0070d-43da-41e1-a163-db240bf3586f.fast5': start processing
00:00:04 - 0/2 reads found
00:00:04 - 'fff0070d-43da-41e1-a163-db240bf3586f.fast5': end processing
! - {} reads from this file have not been found.
--------------------


8000 reads from FAST5 files are not found in FASTQ files.


PS There are only 4000 fast5 in F5
PPS progress "indication" with 4000 files is horrible and slows barapost down to a craw.

**Comment by nikolaichik** [comment]
The original problem seems to be fixed (tested thoroughly on two different datasets), so I'm closing this issue.

Thank you!

PS Proper handling of single_read.fast5 is still highly desirable
